# Generated by Django 6.0.2 on 2026-04-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_pyments_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyments',
            new_name='payments',
        ),
    ]
