# Generated by Django 6.0.2 on 2026-05-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_pyments_order_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='line_address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='line_address_2',
            new_name='address_line_2',
        ),
    ]
